services:
  app-web:
    ports:
      - "80:3000"
    volumes:
      - type: bind
        source: ${HOST_DOWNLOADS_INCOMING:-/srv/mediapolis/downloads/incoming}
        target: ${DOWNLOADS_INCOMING_DIR:-/downloads/incoming}
      - type: bind
        source: ${HOST_PLEX_MOVIES_DIR:-/srv/mediapolis/media/movies}
        target: ${PLEX_MOVIES_DIR:-/media/movies}
      - type: bind
        source: ${HOST_PLEX_TV_DIR:-/srv/mediapolis/media/tv}
        target: ${PLEX_TV_DIR:-/media/tv}

  app-worker:
    volumes:
      - type: bind
        source: ${HOST_DOWNLOADS_INCOMING:-/srv/mediapolis/downloads/incoming}
        target: ${DOWNLOADS_INCOMING_DIR:-/downloads/incoming}
      - type: bind
        source: ${HOST_PLEX_MOVIES_DIR:-/srv/mediapolis/media/movies}
        target: ${PLEX_MOVIES_DIR:-/media/movies}
      - type: bind
        source: ${HOST_PLEX_TV_DIR:-/srv/mediapolis/media/tv}
        target: ${PLEX_TV_DIR:-/media/tv}

  postgres:
    ports: []
